apiVersion: apps/v1
kind: Deployment
metadata:
  name: episode4-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: episode4-frontend
  template:
    metadata:
      labels:
        app: episode4-frontend
    spec:
      containers:
        - name: frontend
          image: <your-dockerhub-username>/episode4-frontend:<tag>
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: episode4-frontend-service
spec:
  selector:
    app: episode4-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
