apiVersion: apps/v1
kind: Deployment
metadata:
  name: episode5-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: episode5-backend
  template:
    metadata:
      labels:
        app: episode5-backend
    spec:
      containers:
        - name: backend
          image: <your-dockerhub-username>/episode5-backend:<tag>
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: episode5-backend-service
spec:
  selector:
    app: episode5-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
